const properties = [
    {
        id: '2424-highland-ave',
        address: '2424 Highland Ave',
        city: 'Shreveport, LA 71104',
        beds: 3,
        baths: 2,
        sqft: 1950,
        ac: 'Central',
        status: 'Rented',
        monthlyRent: 750,
        marketRent: '1,100 - 1,200',
        price: 49000,
        propertyTax: 142.91,
        parishTax: 700.74,
        rentalTime: '7 years',
        notes: '',
        images: [
            'front-exterior.jpg',
            'living-room.jpg',
            'kitchen.jpg',
            'bathroom.jpg',
            'bedroom-corner.jpg',
            'bedroom-window.jpg',
            'bedroom-with-closet.jpg',
            'rear-exterior.jpg'
        ],
        video: '2424-highland-ave-walkthrough.mp4',
        pdf: '2424-Highland-Ave-Shreveport-LA-71104.pdf',
        avm: 84000
    },
    {
        id: '4302-illinois-ave',
        address: '4302 Illinois Ave',
        city: 'Shreveport, LA 71109',
        beds: 3,
        baths: 1,
        sqft: 915,
        ac: 'Window',
        status: 'Vacant',
        monthlyRent: 650,
        marketRent: '700',
        price: 18000,
        propertyTax: 81.73,
        parishTax: 400.76,
        rentalTime: '',
        notes: 'Renovation opportunity',
        images: [
            'front-exterior.jpg',
            'kitchen-with-fireplace.jpg',
            'bathroom-with-toilet.jpg',
            'kitchen-cabinets-detail.jpg',
            'bedroom-with-window-ac.jpg',
            'bedroom-different-angle.jpg',
            'bathroom-vanity-area.jpg',
            'side-exterior-with-steps.jpg',
            'backyard-view.jpg',
            'rear-exterior-view.jpg',
            'back-exterior-angle.jpg'
        ],
        video: null,
        pdf: '4302-Illinois-Ave-Shreveport-LA-71109.pdf',
        avm: 50000
    },
    {
        id: '2536-desoto-st',
        address: '2536 Desoto St',
        city: 'Shreveport, LA 71103',
        beds: 2,
        baths: 1,
        sqft: 900,
        ac: 'Window',
        status: 'Rented',
        monthlyRent: 550,
        marketRent: '750',
        price: 25000,
        propertyTax: 54.61,
        parishTax: 267.78,
        rentalTime: '3 years',
        notes: '',
        images: [
            'front-exterior-with-yard.jpg',
            'front-exterior-with-porch.jpg',
            'electrical-meter-utilities.jpg',
            'street-view-neighborhood.png'
        ],
        video: '2536-desoto-st-walkthrough.mp4',
        pdf: '2536-Desoto-St-Shreveport-LA-71103.pdf',
        avm: null
    },
    {
        id: '250-e-68th-st',
        address: '250 E 68th St',
        city: 'Shreveport, LA 71106',
        beds: 2,
        baths: 1,
        sqft: 850,
        ac: 'Window',
        status: 'Vacant',
        monthlyRent: 550,
        marketRent: '750',
        price: 15000,
        propertyTax: 43.74,
        parishTax: 214.46,
        rentalTime: '',
        notes: 'Renovation opportunity',
        images: [
            'front-exterior.jpg'
        ],
        video: null,
        pdf: null,
        avm: null
    },
    {
        id: '3726-portland-ave',
        address: '3726 Portland Ave',
        city: 'Shreveport, LA 71103',
        beds: 2,
        baths: 1,
        sqft: 1105,
        ac: 'Central',
        status: 'Rented',
        monthlyRent: 550,
        marketRent: '850',
        price: 29000,
        propertyTax: 86.65,
        parishTax: 424.88,
        rentalTime: '8 years',
        notes: '',
        images: [
            'front-exterior-close.jpg',
            'kitchen.jpg',
            'bedroom-with-tv.jpg',
            'bathroom.jpg',
            'bedroom-with-bed.jpg',
            'kitchen-view.jpg'
        ],
        video: '3726-portland-ave-walkthrough.mp4',
        pdf: '3726-Portland-Ave-Shreveport-LA-71103.pdf',
        avm: null
    },
    {
        id: '3730-portland-ave',
        address: '3730 Portland Ave',
        city: 'Shreveport, LA 71103',
        beds: 2,
        baths: 1,
        sqft: 900,
        ac: 'Window',
        status: 'Vacant',
        monthlyRent: 500,
        marketRent: '600',
        price: 12500,
        propertyTax: 4.17,
        parishTax: 20.47,
        rentalTime: '',
        notes: 'Renovation opportunity',
        images: [
            'front-exterior.jpg',
            'living-room.jpg',
            'hallway-interior.jpg',
            'bedroom.jpg',
            'bathroom.jpg',
            'bathroom-detailed.jpg'
        ],
        video: null,
        pdf: null,
        avm: null
    },
    {
        id: '525-sassafras-ave',
        address: '525 Sassafras Ave',
        city: 'Shreveport, LA 71106',
        beds: 2,
        baths: 1,
        sqft: 800,
        ac: 'Window',
        status: 'Rented',
        monthlyRent: 500,
        marketRent: '650',
        price: 27000,
        propertyTax: 55.94,
        parishTax: 274.30,
        rentalTime: '3 years',
        notes: '',
        images: [
            'back-exterior-view.jpg',
            'front-exterior.jpg',
            'interior-bedroom.jpg',
            'side-exterior-view1.jpg',
            'side-exterior-view2.jpg'
        ],
        video: '525-sassafras-ave-walkthrough.mp4',
        pdf: null,
        avm: null
    },
    {
        id: '529-sassafras-ave',
        address: '529 Sassafras Ave',
        city: 'Shreveport, LA 71106',
        beds: 2,
        baths: 1,
        sqft: 800,
        ac: 'Window',
        status: 'Rented',
        monthlyRent: 500,
        marketRent: '650',
        price: 27000,
        propertyTax: 55.94,
        parishTax: 274.30,
        rentalTime: '3 years',
        notes: '',
        images: [
            'street-view-from-road.jpg',
            'front-exterior.jpg',
            'bedroom.jpg',
            'bathroom.jpg',
            'hallway.jpg',
            'laundry-utility-room.jpg',
            'front-exterior-angle.jpg',
            'side-exterior-view.jpg'
        ],
        video: '529-sassafras-ave-walkthrough.mp4',
        pdf: '529-Sassafras-Ave-Shreveport-LA-71106.pdf',
        avm: null
    }
];